global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "insurance-backend"
    metrics_path: /metrics
    static_configs:
      - targets:
          - insurance-backend:8000

rule_files:
  - "alerts.yml"
